<?php
/**
 * Rachel Rae's Rundown — includes/themes.php
 * Theme and font definitions for site customization.
 */

$THEMES = [
    'default' => [
        'name'  => 'Classic Newsprint',
        'vars'  => [], // Uses CSS defaults
    ],
    'rainbow' => [
        'name'  => 'Gay Pride / Rainbow',
        'vars'  => [
            '--cream'        => '#FFF0F5',
            '--warm-white'   => '#FFF8FA',
            '--mustard'      => '#E040A0',
            '--deep-mustard' => '#B8308A',
            '--burnt-orange' => '#FF6B35',
            '--teal'         => '#7B2FBE',
            '--deep-teal'    => '#5A1D8E',
            '--charcoal'     => '#2D1B4E',
            '--ink'          => '#1A0A2E',
            '--warm-gray'    => '#8878A8',
            '--mid-gray'     => '#6B5888',
            '--light-gray'   => '#E8D8F0',
            '--rule-color'   => '#3D2860',
            '--red-accent'   => '#E83060',
            '--blush'        => '#FF90B0',
            '--ticker-bg'    => '#2D1B4E',
            '--ticker-color' => '#FFD700',
            '--deco-bar-bg'  => 'linear-gradient(90deg, #E40303 0%, #E40303 16.66%, #FF8C00 16.66%, #FF8C00 33.33%, #FFED00 33.33%, #FFED00 50%, #008026 50%, #008026 66.66%, #004DFF 66.66%, #004DFF 83.33%, #750787 83.33%, #750787 100%)',
        ],
    ],
    'galaxy' => [
        'name'  => 'Outer Space / Galaxy',
        'vars'  => [
            '--cream'        => '#0D0D1A',
            '--warm-white'   => '#141428',
            '--mustard'      => '#00D4FF',
            '--deep-mustard' => '#0099CC',
            '--burnt-orange' => '#FF6EC7',
            '--teal'         => '#7B68EE',
            '--deep-teal'    => '#5B48CE',
            '--charcoal'     => '#0A0A1A',
            '--ink'          => '#E8E6F0',
            '--warm-gray'    => '#8888AA',
            '--mid-gray'     => '#9999BB',
            '--light-gray'   => '#252540',
            '--rule-color'   => '#1A1A35',
            '--red-accent'   => '#FF4488',
            '--blush'        => '#FF99CC',
            '--ticker-bg'    => '#050510',
            '--ticker-color' => '#00D4FF',
            '--deco-bar-bg'  => 'linear-gradient(90deg, #7B68EE, #FF6EC7, #00D4FF, #7B68EE)',
        ],
    ],
    'sunset' => [
        'name'  => 'Desert Sunset',
        'vars'  => [
            '--cream'        => '#FFF3E0',
            '--warm-white'   => '#FFF8F0',
            '--mustard'      => '#E65100',
            '--deep-mustard' => '#BF360C',
            '--burnt-orange' => '#D32F2F',
            '--teal'         => '#A1520A',
            '--deep-teal'    => '#7A3E08',
            '--charcoal'     => '#3E2723',
            '--ink'          => '#1B0000',
            '--warm-gray'    => '#8D6E63',
            '--mid-gray'     => '#795548',
            '--light-gray'   => '#F0D9C0',
            '--rule-color'   => '#4E342E',
            '--red-accent'   => '#C62828',
            '--blush'        => '#FFAB91',
            '--ticker-bg'    => '#3E2723',
            '--ticker-color' => '#FFB74D',
            '--deco-bar-bg'  => 'linear-gradient(90deg, #FF6F00, #E65100, #D32F2F, #880E4F, #4A148C)',
        ],
    ],
    'retro80s' => [
        'name'  => "Retro 80's Kid",
        'vars'  => [
            '--cream'        => '#1A1A2E',
            '--warm-white'   => '#16213E',
            '--mustard'      => '#FFE400',
            '--deep-mustard' => '#CCB600',
            '--burnt-orange' => '#FF2E63',
            '--teal'         => '#08D9D6',
            '--deep-teal'    => '#06B0AD',
            '--charcoal'     => '#0F0F1A',
            '--ink'          => '#EAEAEA',
            '--warm-gray'    => '#A0A0C0',
            '--mid-gray'     => '#B0B0D0',
            '--light-gray'   => '#252545',
            '--rule-color'   => '#1A1A35',
            '--red-accent'   => '#FF2E63',
            '--blush'        => '#FF6B9D',
            '--ticker-bg'    => '#0F0F1A',
            '--ticker-color' => '#FFE400',
            '--deco-bar-bg'  => 'repeating-linear-gradient(90deg, #FF2E63 0px, #FF2E63 4px, #FFE400 4px, #FFE400 8px, #08D9D6 8px, #08D9D6 12px, #0F0F1A 12px, #0F0F1A 16px)',
        ],
    ],
    'walmart' => [
        'name'  => 'Walmart',
        'vars'  => [
            '--cream'        => '#F0F4F8',
            '--warm-white'   => '#FFFFFF',
            '--mustard'      => '#FFC220',
            '--deep-mustard' => '#E5A800',
            '--burnt-orange' => '#004C91',
            '--teal'         => '#007DC6',
            '--deep-teal'    => '#005A8E',
            '--charcoal'     => '#041E42',
            '--ink'          => '#2E2F32',
            '--warm-gray'    => '#76787B',
            '--mid-gray'     => '#585A5C',
            '--light-gray'   => '#E0E5EB',
            '--rule-color'   => '#041E42',
            '--red-accent'   => '#004C91',
            '--blush'        => '#78B9E7',
            '--ticker-bg'    => '#041E42',
            '--ticker-color' => '#FFC220',
            '--deco-bar-bg'  => 'repeating-linear-gradient(90deg, #004C91 0px, #004C91 3px, #FFC220 3px, #FFC220 6px, #FFFFFF 6px, #FFFFFF 9px)',
        ],
    ],
];

$FONT_OPTIONS = [
    'default' => [
        'name'      => 'Classic (Garamond)',
        'headline'  => "'Cormorant Garamond', Georgia, serif",
        'body'      => "'EB Garamond', Georgia, serif",
        'mono'      => "'DM Mono', monospace",
    ],
    'playfair' => [
        'name'      => 'Playfair Display',
        'headline'  => "'Playfair Display', Georgia, serif",
        'body'      => "'Lora', Georgia, serif",
        'mono'      => "'DM Mono', monospace",
    ],
    'oldstandard' => [
        'name'      => 'Old Standard',
        'headline'  => "'Old Standard TT', Georgia, serif",
        'body'      => "'Crimson Text', Georgia, serif",
        'mono'      => "'DM Mono', monospace",
    ],
];
